Line = input ( "Beautiful is better than ugly" )
Line2 = "Beautiful is better than ugly".upper()
Line.find ('better')
Line.find ('is')
Line.find ('never')
print = (Line.replace ('i', '&', 10))
print = (Line)
print = (Line2)